<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-2GC0944" failures="2" tests="4" name="PetTest" time="13.958" errors="0" timestamp="2025-08-20T01:26:50 IST">
  <testcase classname="api.test.UserTests2" name="testPostUser" time="4.994"/>
  <testcase classname="api.test.UserTests2" name="testGetUserByName" time="3.371">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testGetUserByName(UserTests2.java:64)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testGetUserByName -->
  <testcase classname="api.test.UserTests2" name="testUpdateUserByName" time="2.727"/>
  <testcase classname="api.test.UserTests2" name="testDeleteUserByName" time="1.263">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.UserTests2.testDeleteUserByName(UserTests2.java:98)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
... Removed 36 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteUserByName -->
</testsuite> <!-- PetTest -->
